#!/usr/bin/env python3
import argparse
import pathlib
from string import Template

TEMPLATE_CMAKELISTS = Template("""cmake_minimum_required(VERSION 3.22)
project($name LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 23)
add_executable($name src/main.cpp)
""")

TEMPLATE_MAIN = Template(
    '#include <iostream>\nint main(){ std::cout << "Hello from $name\\n"; }\n'
)

def cmd_new(args):
    root = pathlib.Path(args.name)
    (root / "src").mkdir(parents=True, exist_ok=True)

    (root / "CMakeLists.txt").write_text(
        TEMPLATE_CMAKELISTS.substitute(name=args.name), encoding="utf-8"
    )
    (root / "src/main.cpp").write_text(
        TEMPLATE_MAIN.substitute(name=args.name), encoding="utf-8"
    )
    (root / "README.md").write_text(
        f"# {args.name}\nGenerated by cpp-forge.\n", encoding="utf-8"
    )
    print(f"✅ Created {args.name}")

def main():
    ap = argparse.ArgumentParser("cpp-forge")
    sub = ap.add_subparsers(dest="cmd", required=True)

    ap_new = sub.add_parser("new", help="Create a new C++ project")
    ap_new.add_argument("name")
    ap_new.set_defaults(func=cmd_new)

    args = ap.parse_args()
    args.func(args)

if __name__ == "__main__":
    main()
